use crate::model::Level;

/// 日语播客策展。数据与 memshare `podcast-seed` 一致，只保留日语节目。
#[derive(Debug, Clone, Copy)]
pub struct CategorySeed {
    pub id: &'static str,
    pub title: &'static str,
    pub subtitle: &'static str,
    pub sort_order: i32,
}

#[derive(Debug, Clone, Copy)]
pub struct ShowSeed {
    pub id: &'static str,
    pub category_id: &'static str,
    pub rss_url: &'static str,
    pub title: &'static str,
    pub author: &'static str,
    pub cover_color: &'static str,
    pub cover_label: &'static str,
    pub level: Level,
    pub tagline: &'static str,
    pub description: &'static str,
    pub sort_order: i32,
}

pub const CATEGORIES: &[CategorySeed] = &[
    CategorySeed {
        id: "easy_listen",
        title: "轻松起听",
        subtitle: "从清晰简短的日语内容开始",
        sort_order: 0,
    },
    CategorySeed {
        id: "daily_talk",
        title: "日常对话",
        subtitle: "在生活场景里听自然表达",
        sort_order: 1,
    },
    CategorySeed {
        id: "culture_life",
        title: "文化生活",
        subtitle: "聊聊习俗、兴趣与日常碎语",
        sort_order: 2,
    },
    CategorySeed {
        id: "news_society",
        title: "新闻与社会",
        subtitle: "用新闻和时事练真实听力",
        sort_order: 3,
    },
];

pub const SHOWS: &[ShowSeed] = &[
    ShowSeed {
        id: "mukashi-banashi",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/b15fc38/podcast/rss",
        title: "【民話朗読】おばあちゃんの日本昔ばなし",
        author: "ヤマネコ ギン",
        cover_color: "#e8a87c",
        cover_label: "昔",
        level: Level::Beginner,
        tagline: "围炉听民话",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "ehon-yomikikase",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/11a74f5c/podcast/rss",
        title: "童話、絵本の読みきかせ",
        author: "かやちゃん",
        cover_color: "#f6ad55",
        cover_label: "絵",
        level: Level::Beginner,
        tagline: "翻开故事书",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "kotonoha",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/9e8ef8ac/podcast/rss",
        title: "日本語の会話のpodcast −ことのは−",
        author: "日本語の先生：ことのは",
        cover_color: "#68d391",
        cover_label: "こと",
        level: Level::Beginner,
        tagline: "对话里的习俗",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "teppei",
        category_id: "easy_listen",
        rss_url: "https://nihongoconteppei.com/feed/podcast",
        title: "Japanese podcast for beginners (Nihongo con Teppei)",
        author: "Teppei",
        cover_color: "#63b3ed",
        cover_label: "Te",
        level: Level::Beginner,
        tagline: "每天几分钟入门",
        description: "",
        sort_order: 3,
    },
    ShowSeed {
        id: "sakura-tips",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/3c2daac8/podcast/rss",
        title: "SAKURA TIPS｜Listen to Japanese",
        author: "Mari",
        cover_color: "#f687b3",
        cover_label: "桜",
        level: Level::Beginner,
        tagline: "短句练听力",
        description: "",
        sort_order: 4,
    },
    ShowSeed {
        id: "learn-noriko",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/1380f800/podcast/rss",
        title: "Learn Japanese with Noriko",
        author: "Japanese with Noriko",
        cover_color: "#9f7aea",
        cover_label: "No",
        level: Level::Beginner,
        tagline: "清晰慢速讲解",
        description: "",
        sort_order: 5,
    },
    ShowSeed {
        id: "sukoshi-yukkuri",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/5274bc54/podcast/rss",
        title: "少しゆっくり日本語 Listening Practice with Native Japanese",
        author: "Ryuichi",
        cover_color: "#4fd1c5",
        cover_label: "ゆ",
        level: Level::Beginner,
        tagline: "稍慢一点的日语",
        description: "",
        sort_order: 6,
    },
    ShowSeed {
        id: "jane-su",
        category_id: "daily_talk",
        rss_url: "https://feeds.megaphone.fm/TBS1408470359",
        title: "ジェーン・スー　生活は踊る",
        author: "TBS RADIO",
        cover_color: "#ed8936",
        cover_label: "JS",
        level: Level::Beginner,
        tagline: "都市生活谈资",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "radio-magazine",
        category_id: "daily_talk",
        rss_url: "https://feeds.megaphone.fm/rm",
        title: "武田砂鉄 ラジオマガジン",
        author: "文化放送PodcastQR",
        cover_color: "#718096",
        cover_label: "砂",
        level: Level::Advanced,
        tagline: "社会观察电台",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "kemio",
        category_id: "daily_talk",
        rss_url: "https://anchor.fm/s/f0e04264/podcast/rss",
        title: "kemioの言わせて言うだけEverything",
        author: "UNICORN.inc",
        cover_color: "#fc8181",
        cover_label: "ke",
        level: Level::Advanced,
        tagline: "潮流话题闲聊",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "small-talk",
        category_id: "daily_talk",
        rss_url: "https://anchor.fm/s/88ddddc/podcast/rss",
        title: "Let’s learn Japanese from small talk!",
        author: "small talk in Japanese",
        cover_color: "#48bb78",
        cover_label: "ST",
        level: Level::Beginner,
        tagline: "闲聊里学表达",
        description: "",
        sort_order: 3,
    },
    ShowSeed {
        id: "yuyu-nihongo",
        category_id: "daily_talk",
        rss_url: "https://anchor.fm/s/cda85d4/podcast/rss",
        title: "YUYUの日本語Podcast【Japanese Podcast】",
        author: "YUYU NIHONGO",
        cover_color: "#ecc94b",
        cover_label: "YU",
        level: Level::Beginner,
        tagline: "轻松日语碎碎念",
        description: "",
        sort_order: 4,
    },
    ShowSeed {
        id: "ringo-kana",
        category_id: "culture_life",
        rss_url: "https://anchor.fm/s/f39b8eb4/podcast/rss",
        title: "りんご屋KANAのひとりごと | 日本語を話そう聞こう！",
        author: "Kana",
        cover_color: "#e53e3e",
        cover_label: "り",
        level: Level::Beginner,
        tagline: "日常日语碎语",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "nihongo-sensei",
        category_id: "culture_life",
        rss_url: "https://anchor.fm/s/76b8cd08/podcast/rss",
        title: "Japanese learning podcast (by Japanese Nihongo Sensei)",
        author: "Japanese Nihongo Sensei",
        cover_color: "#38b2ac",
        cover_label: "先",
        level: Level::Beginner,
        tagline: "老师答疑解惑",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "nihongo-short",
        category_id: "culture_life",
        rss_url: "https://anchor.fm/s/81109d44/podcast/rss",
        title: "Nihongo Short Story by Noriko",
        author: "Learn Japanese with stories!",
        cover_color: "#d69e2e",
        cover_label: "短",
        level: Level::Beginner,
        tagline: "短篇故事听读",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "nhk-news",
        category_id: "news_society",
        rss_url: "https://www.nhk.or.jp/s-media/news/podcast/list/v1/all.xml",
        title: "NHKラジオニュース",
        author: "NHK",
        cover_color: "#e53e3e",
        cover_label: "NHK",
        level: Level::Advanced,
        tagline: "日语新闻速报",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "news-slow-jp",
        category_id: "news_society",
        rss_url: "https://newsinslowjapanese.org/feed/podcast/",
        title: "News in Slow Japanese / The Podcast",
        author: "Sakura",
        cover_color: "#2b6cb0",
        cover_label: "NS",
        level: Level::Advanced,
        tagline: "慢速新闻精听",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "bilingual-news",
        category_id: "news_society",
        rss_url: "https://rss.libsyn.com/shows/46528/destinations/154797.xml",
        title: "バイリンガルニュース (Bilingual News)",
        author: "Michael & Mami",
        cover_color: "#805ad5",
        cover_label: "BN",
        level: Level::Advanced,
        tagline: "双语时事闲聊",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "nhk-easy",
        category_id: "news_society",
        rss_url: "https://www3.nhk.or.jp/nhkworld/lesson/en/rss/podcast.xml",
        title: "Easy Japanese: Conversation Lessons | NHK WORLD-JAPAN",
        author: "NHK WORLD-JAPAN",
        cover_color: "#c53030",
        cover_label: "EZ",
        level: Level::Beginner,
        tagline: "NHK 简易会话",
        description: "",
        sort_order: 3,
    },
];

/// RSS 主机只用于标记来源。Anchor、Megaphone、WordPress、Libsyn、NHK 走同一套解析。
pub fn platform_of(rss_url: &str) -> &'static str {
    if rss_url.contains("anchor.fm") {
        "anchor"
    } else if rss_url.contains("megaphone.fm") {
        "megaphone"
    } else if rss_url.contains("libsyn.com") {
        "libsyn"
    } else if rss_url.contains("nhk.or.jp") {
        "nhk"
    } else if rss_url.contains("/feed/podcast") {
        "wordpress"
    } else {
        "rss"
    }
}
