use crate::model::Level;

/// 日语播客策展。分类、标题、短描述和难度与 App 目录一致。
#[derive(Debug, Clone, Copy)]
pub struct CategorySeed {
    pub id: &'static str,
    pub title: &'static str,
    pub subtitle: &'static str,
    pub sort_order: i32,
}

#[derive(Debug, Clone, Copy)]
pub struct ShowSeed {
    pub id: &'static str,
    pub category_id: &'static str,
    pub rss_url: &'static str,
    pub title: &'static str,
    pub author: &'static str,
    pub cover_color: &'static str,
    pub cover_label: &'static str,
    pub level: Level,
    pub tagline: &'static str,
    pub description: &'static str,
    pub sort_order: i32,
}

pub const CATEGORIES: &[CategorySeed] = &[
    CategorySeed {
        id: "easy_listen",
        title: "轻松起听",
        subtitle: "从清晰简短的日语内容开始",
        sort_order: 0,
    },
    CategorySeed {
        id: "daily_talk",
        title: "日常对话",
        subtitle: "在生活场景里听自然表达",
        sort_order: 1,
    },
    CategorySeed {
        id: "culture_life",
        title: "文化生活",
        subtitle: "从街道、味道与生活场景认识日本",
        sort_order: 2,
    },
    CategorySeed {
        id: "news_society",
        title: "新闻与社会",
        subtitle: "从新闻里读懂当下",
        sort_order: 3,
    },
    CategorySeed {
        id: "learning",
        title: "学习与成长",
        subtitle: "用知识型播客把思路听清",
        sort_order: 4,
    },
    CategorySeed {
        id: "tech_life",
        title: "科技与数字生活",
        subtitle: "从身边技术看世界",
        sort_order: 5,
    },
    CategorySeed {
        id: "history",
        title: "历史与人文",
        subtitle: "从故事、观念与现场进入时代",
        sort_order: 6,
    },
    CategorySeed {
        id: "pop_culture",
        title: "书影音与流行文化",
        subtitle: "从作品走进语言与文化",
        sort_order: 7,
    },
];

pub const SHOWS: &[ShowSeed] = &[
    ShowSeed {
        id: "mukashi-banashi",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/b15fc38/podcast/rss",
        title: "【民話朗読】おばあちゃんの日本昔ばなし",
        author: "ヤマネコ ギン",
        cover_color: "#e8a87c",
        cover_label: "昔",
        level: Level::Beginner,
        tagline: "围炉听民话",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "ehon-yomikikase",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/11a74f5c/podcast/rss",
        title: "童話、絵本の読みきかせ",
        author: "かやちゃん",
        cover_color: "#f6ad55",
        cover_label: "絵",
        level: Level::Beginner,
        tagline: "翻开故事书",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "kotonoha",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/9e8ef8ac/podcast/rss",
        title: "日本語の会話のpodcast −ことのは−",
        author: "日本語の先生：ことのは",
        cover_color: "#68d391",
        cover_label: "こと",
        level: Level::Beginner,
        tagline: "对话里的习俗",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "slow-japanese",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/6cbdbe8/podcast/rss",
        title: "日本語を大切にしたい Slow Japanese Podcast",
        author: "こんち",
        cover_color: "#f6e05e",
        cover_label: "慢",
        level: Level::Beginner,
        tagline: "跟着思路走",
        description: "",
        sort_order: 3,
    },
    ShowSeed {
        id: "real-behavior",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/4ce7a51c/podcast/rss",
        title: "超リアルな行動心理学",
        author: "FERMONDO",
        cover_color: "#4c51bf",
        cover_label: "心",
        level: Level::Advanced,
        tagline: "看懂行为背后",
        description: "",
        sort_order: 4,
    },
    ShowSeed {
        id: "chokai",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/1fe5323c/podcast/rss",
        title: "日本語の聴解のためのPodcast",
        author: "あかね的日本語教室",
        cover_color: "#ed64a6",
        cover_label: "聴",
        level: Level::Advanced,
        tagline: "从小事听起",
        description: "",
        sort_order: 5,
    },
    ShowSeed {
        id: "kokoro-hogu",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/38882bc8/podcast/rss",
        title: "心をほぐすラジオ",
        author: "幸あれこ",
        cover_color: "#f687b3",
        cover_label: "ほ",
        level: Level::Advanced,
        tagline: "把心事说开",
        description: "",
        sort_order: 6,
    },
    ShowSeed {
        id: "everyday-japanese",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/25d02b0c/podcast/rss",
        title: "Everyday Japanese Podcast",
        author: "Sayuri Saying",
        cover_color: "#2f855a",
        cover_label: "EJ",
        level: Level::Advanced,
        tagline: "听见季节日常",
        description: "",
        sort_order: 7,
    },
    ShowSeed {
        id: "yuyu-nihongo",
        category_id: "easy_listen",
        rss_url: "https://anchor.fm/s/cda85d4/podcast/rss",
        title: "YUYUの日本語Podcast【Japanese Podcast】",
        author: "YUYU NIHONGO",
        cover_color: "#63b3ed",
        cover_label: "YU",
        level: Level::Advanced,
        tagline: "话题随处可见",
        description: "",
        sort_order: 8,
    },
    ShowSeed {
        id: "easy-japanese",
        category_id: "easy_listen",
        rss_url: "https://feed.podbean.com/easyjapanese/feed.xml",
        title: "EASY JAPANESE PODCAST",
        author: "MASA and ASAMI",
        cover_color: "#c6a15b",
        cover_label: "EA",
        level: Level::Advanced,
        tagline: "词语落在日常",
        description: "",
        sort_order: 9,
    },
    ShowSeed {
        id: "jane-su",
        category_id: "daily_talk",
        rss_url: "https://feeds.megaphone.fm/TBS1408470359",
        title: "ジェーン・スー 生活は踊る",
        author: "TBS RADIO",
        cover_color: "#ed8936",
        cover_label: "JS",
        level: Level::Beginner,
        tagline: "午间生活万花筒",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "radio-magazine",
        category_id: "daily_talk",
        rss_url: "https://feeds.megaphone.fm/rm",
        title: "武田砂鉄 ラジオマガジン",
        author: "文化放送PodcastQR",
        cover_color: "#718096",
        cover_label: "砂",
        level: Level::Advanced,
        tagline: "与作者把话谈深",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "kemio",
        category_id: "daily_talk",
        rss_url: "https://anchor.fm/s/f0e04264/podcast/rss",
        title: "kemioの言わせて言うだけEverything",
        author: "UNICORN.inc",
        cover_color: "#805ad5",
        cover_label: "ke",
        level: Level::Advanced,
        tagline: "城市人自白录",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "sanmai-oroshi",
        category_id: "daily_talk",
        rss_url: "https://feeds.megaphone.fm/NCB9110418240",
        title: "武田鉄矢・今朝の三枚おろし",
        author: "文化放送PodcastQR",
        cover_color: "#a0aec0",
        cover_label: "鉄",
        level: Level::Advanced,
        tagline: "一题慢慢说透",
        description: "",
        sort_order: 3,
    },
    ShowSeed {
        id: "nichiyo-tengoku",
        category_id: "daily_talk",
        rss_url: "https://feeds.megaphone.fm/TBS2679398439",
        title: "安住紳一郎の日曜天国",
        author: "TBS RADIO",
        cover_color: "#2b6cb0",
        cover_label: "天",
        level: Level::Advanced,
        tagline: "周日话头真会拐",
        description: "",
        sort_order: 4,
    },
    ShowSeed {
        id: "around-forty",
        category_id: "daily_talk",
        rss_url: "https://stand.fm/rss/6385850482838c6aa303a475",
        title: "アラフォーの正解のないはなし",
        author: "正解のないはなし",
        cover_color: "#d53f8c",
        cover_label: "ア",
        level: Level::Advanced,
        tagline: "两种活法对照看",
        description: "",
        sort_order: 5,
    },
    ShowSeed {
        id: "tabete-shabette",
        category_id: "daily_talk",
        rss_url: "https://feeds.megaphone.fm/TBS5986196202",
        title: "ぼる塾あんりと田辺の食べて喋って",
        author: "TBS RADIO",
        cover_color: "#dd6b20",
        cover_label: "食",
        level: Level::Advanced,
        tagline: "零食拆开就开聊",
        description: "",
        sort_order: 6,
    },
    ShowSeed {
        id: "yattamon-doitsu",
        category_id: "daily_talk",
        rss_url: "https://anchor.fm/s/60ea0d70/podcast/rss",
        title: "やったもん勝ちドイツPodcast",
        author: "Kohei Hirotsu",
        cover_color: "#2c5282",
        cover_label: "独",
        level: Level::Advanced,
        tagline: "柏林日子日日更",
        description: "",
        sort_order: 7,
    },
    ShowSeed {
        id: "tonari-zatsudan",
        category_id: "daily_talk",
        rss_url: "https://feeds.megaphone.fm/TBS6714057012",
        title: "となりの雑談",
        author: "TBS RADIO",
        cover_color: "#1a202c",
        cover_label: "雑",
        level: Level::Expert,
        tagline: "偷听邻桌闲谈",
        description: "",
        sort_order: 8,
    },
    ShowSeed {
        id: "kayobi-kinyobi",
        category_id: "daily_talk",
        rss_url: "https://anchor.fm/s/100cc50b4/podcast/rss",
        title: "火曜日と金曜日のラジオ",
        author: "火曜日と金曜日のラジオ",
        cover_color: "#f6e05e",
        cover_label: "火",
        level: Level::Expert,
        tagline: "三人把感觉聊明",
        description: "",
        sort_order: 9,
    },
    ShowSeed {
        id: "voice-of-food",
        category_id: "culture_life",
        rss_url: "https://feed.sonicbowl.cloud/rss/a72229b2-682a-4c6f-90c7-5496a0ad1cd3/",
        title: "味な副音声 ～voice of food～",
        author: "J-WAVE",
        cover_color: "#f6ad55",
        cover_label: "味",
        level: Level::Advanced,
        tagline: "味道自有立场",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "naniwa-chiri",
        category_id: "culture_life",
        rss_url: "https://feeds.megaphone.fm/mnc",
        title: "予備校講師 村瀬哲史のナニワ地理学～関西不動産情報センターＫＲＩＣ presents～",
        author: "MBSラジオ",
        cover_color: "#38a169",
        cover_label: "地",
        level: Level::Advanced,
        tagline: "跟着街区读城",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "kiku-kosume",
        category_id: "culture_life",
        rss_url: "https://feed.sonicbowl.cloud/rss/d8ef24fd-24de-4e68-9a59-bf8ff070a4b3/",
        title: "福本敦子のきくこすめ",
        author: "J-WAVE",
        cover_color: "#d69e2e",
        cover_label: "き",
        level: Level::Advanced,
        tagline: "把日子过柔软",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "culture-collage",
        category_id: "culture_life",
        rss_url: "https://feed.sonicbowl.cloud/rss/2ca74fbf-e686-4eb8-957c-223598b3d936/",
        title: "ARTS COUNCIL TOKYO CULTURE COLLAGE",
        author: "J-WAVE",
        cover_color: "#ed64a6",
        cover_label: "AC",
        level: Level::Advanced,
        tagline: "十分钟进现场",
        description: "",
        sort_order: 3,
    },
    ShowSeed {
        id: "arukikata",
        category_id: "culture_life",
        rss_url: "https://anchor.fm/s/10076fc90/podcast/rss",
        title: "地球の歩き方 　旅の雑談",
        author: "地球の歩き方",
        cover_color: "#e53e3e",
        cover_label: "歩",
        level: Level::Advanced,
        tagline: "听编辑聊远方",
        description: "",
        sort_order: 4,
    },
    ShowSeed {
        id: "tck",
        category_id: "culture_life",
        rss_url: "https://crossactnet.com/feed/podcast/",
        title: "日本の居場所と未来を創る！TCK(帰国子女)　Podcast",
        author: "育ちネット多文化CROSS",
        cover_color: "#3182ce",
        cover_label: "TC",
        level: Level::Advanced,
        tagline: "把家说清楚",
        description: "",
        sort_order: 5,
    },
    ShowSeed {
        id: "plenus-rice",
        category_id: "culture_life",
        rss_url: "https://feed.sonicbowl.cloud/rss/36b478ce-bfc7-4ffa-84dd-b48f70840872/",
        title: "PLENUS RICE TO BE HERE",
        author: "J-WAVE",
        cover_color: "#dd6b20",
        cover_label: "米",
        level: Level::Advanced,
        tagline: "饭桌里的地方志",
        description: "",
        sort_order: 6,
    },
    ShowSeed {
        id: "fuku-senbi",
        category_id: "culture_life",
        rss_url: "https://anchor.fm/s/b61cc65c/podcast/rss",
        title: "30歳からの服選び",
        author: "松本典子",
        cover_color: "#d53f8c",
        cover_label: "服",
        level: Level::Advanced,
        tagline: "衣柜问题现场解",
        description: "",
        sort_order: 7,
    },
    ShowSeed {
        id: "ourhome",
        category_id: "culture_life",
        rss_url: "https://anchor.fm/s/f590946c/podcast/rss",
        title: "OURHOME 暮らす働く\"ちょうどいい\"ラジオ",
        author: "Emi-OURHOME",
        cover_color: "#2b6cb0",
        cover_label: "家",
        level: Level::Advanced,
        tagline: "听一家人拿主意",
        description: "",
        sort_order: 8,
    },
    ShowSeed {
        id: "itte-miho",
        category_id: "culture_life",
        rss_url: "https://www.omnycontent.com/d/playlist/67122501-9b17-4d77-84bd-a93d00dc791e/e8feb173-1be4-4ae7-ad2c-b14500b9aa50/560e5c8f-d404-4da3-9dcc-b14500bbf05b/podcast.rss",
        title: "熊谷実帆の行ってミホ！やってミホ！",
        author: "ニッポン放送",
        cover_color: "#ed64a6",
        cover_label: "ミ",
        level: Level::Advanced,
        tagline: "先替你去一趟",
        description: "",
        sort_order: 9,
    },
    ShowSeed {
        id: "world-report",
        category_id: "news_society",
        rss_url: "https://www.nhk.or.jp/s-media/F519/podcast/list/v1/all.xml",
        title: "ワールドリポート　ＮＨＫラジオ「マイあさ！」",
        author: "NHK",
        cover_color: "#a0aec0",
        cover_label: "世",
        level: Level::Beginner,
        tagline: "从一地看世界",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "cozy-up",
        category_id: "news_society",
        rss_url: "https://www.omnycontent.com/d/playlist/67122501-9b17-4d77-84bd-a93d00dc791e/3c31cad9-230a-4a5f-b487-a9de001adcdd/47a5ec59-4c22-496d-b71d-b2a4001ebd5d/podcast.rss",
        title: "飯田浩司のOK! Cozy up! Podcast",
        author: "ニッポン放送",
        cover_color: "#2b6cb0",
        cover_label: "OK",
        level: Level::Advanced,
        tagline: "晨间追问来处",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "young-nikkei",
        category_id: "news_society",
        rss_url: "https://feeds.megaphone.fm/young",
        title: "ヤング日経（サクッとわかるビジネスニュース）",
        author: "ラジオNIKKEI",
        cover_color: "#e53e3e",
        cover_label: "日",
        level: Level::Advanced,
        tagline: "商业风向快切",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "standby",
        category_id: "news_society",
        rss_url: "https://feeds.megaphone.fm/TBS3478276531",
        title: "森本毅郎・スタンバイ！",
        author: "TBS RADIO",
        cover_color: "#718096",
        cover_label: "ス",
        level: Level::Advanced,
        tagline: "晨报拼着听",
        description: "",
        sort_order: 3,
    },
    ShowSeed {
        id: "yomiuri-news",
        category_id: "news_society",
        rss_url: "https://www.omnycontent.com/d/playlist/1ac836f7-a55f-4b30-8e98-aeac011f8199/98d8085a-3352-4712-b1a8-b10f003f4ba3/92340250-9561-4fdb-91a8-b10f0041d8d0/podcast.rss",
        title: "読売新聞音声ニュース",
        author: "読売新聞ポッドキャスト",
        cover_color: "#c53030",
        cover_label: "読",
        level: Level::Advanced,
        tagline: "晚报直接朗读",
        description: "",
        sort_order: 4,
    },
    ShowSeed {
        id: "otake",
        category_id: "news_society",
        rss_url: "https://feeds.megaphone.fm/NCB7274439885",
        title: "大竹紳士交遊録 - 大竹まことゴールデンラジオ！",
        author: "文化放送PodcastQR",
        cover_color: "#6b46c1",
        cover_label: "交",
        level: Level::Advanced,
        tagline: "换个嘉宾开火",
        description: "",
        sort_order: 5,
    },
    ShowSeed {
        id: "anatoku",
        category_id: "news_society",
        rss_url: "https://anchor.fm/s/fc008d48/podcast/rss",
        title: "西日本新聞 あな特Podcast",
        author: "西日本新聞社",
        cover_color: "#2b6cb0",
        cover_label: "あ",
        level: Level::Advanced,
        tagline: "疑问送去追查",
        description: "",
        sort_order: 6,
    },
    ShowSeed {
        id: "nhk-news",
        category_id: "news_society",
        rss_url: "https://www.nhk.or.jp/s-media/news/podcast/list/v1/all.xml",
        title: "NHKラジオニュース",
        author: "NHK",
        cover_color: "#e53e3e",
        cover_label: "NHK",
        level: Level::Advanced,
        tagline: "整点新闻不断档",
        description: "",
        sort_order: 7,
    },
    ShowSeed {
        id: "media-talk",
        category_id: "news_society",
        rss_url: "https://www.omnycontent.com/d/playlist/1e3bd144-9b57-451a-93cf-ac0e00e74446/50382bb4-3af3-4250-8ddc-ac0f0033ceb5/07a1de49-67cf-4714-8581-ac1000059302/podcast.rss",
        title: "MEDIA TALK メディアトーク",
        author: "朝日新聞ポッドキャスト",
        cover_color: "#d53f8c",
        cover_label: "MT",
        level: Level::Expert,
        tagline: "媒体也得自审",
        description: "",
        sort_order: 8,
    },
    ShowSeed {
        id: "kyodo",
        category_id: "news_society",
        rss_url: "https://www.omnycontent.com/d/playlist/6c1d6f91-c940-481f-98bc-af8200beb4a9/b9715a87-f925-4804-a155-af8e003728dc/fc5cf3b3-7c9a-4f1f-97f9-af8e003728fd/podcast.rss",
        title: "共同通信Podcastーニュースの裏側も、多言語学習も、経済もー",
        author: "共同通信社",
        cover_color: "#c53030",
        cover_label: "共",
        level: Level::Expert,
        tagline: "通讯社排班表",
        description: "",
        sort_order: 9,
    },
    ShowSeed {
        id: "kid-news",
        category_id: "learning",
        rss_url: "https://anchor.fm/s/10afb9540/podcast/rss",
        title: "Kids' News - キッズニュース",
        author: "Rina Arai / あらい りな",
        cover_color: "#f6e05e",
        cover_label: "KN",
        level: Level::Beginner,
        tagline: "先把大词讲小",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "kenkyu-kurashi",
        category_id: "learning",
        rss_url: "https://rss.listen.style/p/jimpei/rss",
        title: "研究者がそばにいるくらし",
        author: "心理学者じんぺー",
        cover_color: "#718096",
        cover_label: "研",
        level: Level::Beginner,
        tagline: "论文落进日常",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "kiku-dora",
        category_id: "learning",
        rss_url: "https://anchor.fm/s/d5b21a1c/podcast/rss",
        title: "きくドラ",
        author: "きくドラ～ラジオドラマで聴く名作文学～",
        cover_color: "#e53e3e",
        cover_label: "ド",
        level: Level::Beginner,
        tagline: "一集听完名作",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "yuru-gengogaku",
        category_id: "learning",
        rss_url: "https://api.robotstart.jp/api/v1/feeds/35d00481/get-feeds/podcast",
        title: "ゆる言語学ラジオ",
        author: "Yuru Gengogaku Radio",
        cover_color: "#38a169",
        cover_label: "言",
        level: Level::Advanced,
        tagline: "拆句子找门道",
        description: "",
        sort_order: 3,
    },
    ShowSeed {
        id: "homo-ludens",
        category_id: "learning",
        rss_url: "https://anchor.fm/s/626fdcd8/podcast/rss",
        title: "ホモルーデンスの朝",
        author: "めざまし代わりの遊びのお話",
        cover_color: "#d69e2e",
        cover_label: "遊",
        level: Level::Advanced,
        tagline: "把玩当方法",
        description: "",
        sort_order: 4,
    },
    ShowSeed {
        id: "kokoro-reskilling",
        category_id: "learning",
        rss_url: "https://anchor.fm/s/f31a405c/podcast/rss",
        title: "気づくと変わる心理学 〜心のリスキリング〜",
        author: "TAシナジー研究所",
        cover_color: "#f6e05e",
        cover_label: "気",
        level: Level::Advanced,
        tagline: "一条法则一集",
        description: "",
        sort_order: 5,
    },
    ShowSeed {
        id: "rurouni-shinri",
        category_id: "learning",
        rss_url: "https://anchor.fm/s/1052a9418/podcast/rss",
        title: "るろうに 勇気が出る心理学ラジオ for Podcast Spotify",
        author: "るろうに｜心理カウンセラー",
        cover_color: "#63b3ed",
        cover_label: "勇",
        level: Level::Advanced,
        tagline: "给社交松绑",
        description: "",
        sort_order: 6,
    },
    ShowSeed {
        id: "hori-sensei",
        category_id: "learning",
        rss_url: "https://stand.fm/rss/6640bf91875ed51dcfa98b71",
        title: "ほりせんせいの「知るは楽しみなり」",
        author: "ほりきよし",
        cover_color: "#fc8181",
        cover_label: "ほ",
        level: Level::Advanced,
        tagline: "一周想透一题",
        description: "",
        sort_order: 7,
    },
    ShowSeed {
        id: "retaction",
        category_id: "learning",
        rss_url: "https://anchor.fm/s/f4b89cec/podcast/rss",
        title: "ReTACTION Radio ～知とビジネスと仏教の交差点～",
        author: "龍谷大学 × Chronicle",
        cover_color: "#c53030",
        cover_label: "Re",
        level: Level::Expert,
        tagline: "研究走进餐桌",
        description: "",
        sort_order: 8,
    },
    ShowSeed {
        id: "w-nagai",
        category_id: "learning",
        rss_url: "https://feed.sonicbowl.cloud/rss/eb8cdf54-d5e8-47c4-836b-0b2576c81572/",
        title: "永井玲衣×長井優希乃『Wナガイと哲学対話』",
        author: "J-WAVE",
        cover_color: "#d53f8c",
        cover_label: "哲",
        level: Level::Expert,
        tagline: "小问题慢慢想",
        description: "",
        sort_order: 9,
    },
    ShowSeed {
        id: "naoto-hakase",
        category_id: "tech_life",
        rss_url: "https://anchor.fm/s/fae8a3dc/podcast/rss",
        title: "ナオト博士の地球のこと知ってる！？",
        author: "ナオト博士",
        cover_color: "#2b6cb0",
        cover_label: "ナ",
        level: Level::Advanced,
        tagline: "地球反常识",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "dotasai",
        category_id: "tech_life",
        rss_url: "https://anchor.fm/s/eb006cc0/podcast/rss",
        title: "准教授・五十嵐美樹のドタバタ科学ラジオ「ドタサイ」",
        author: "五十嵐美樹",
        cover_color: "#e53e3e",
        cover_label: "ド",
        level: Level::Advanced,
        tagline: "把科学带上路",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "scientalk",
        category_id: "tech_life",
        rss_url: "https://rss.listen.style/p/scientalk/rss",
        title: "サイエントーク",
        author: "レンとエマ",
        cover_color: "#1a365d",
        cover_label: "サ",
        level: Level::Advanced,
        tagline: "闲聊里有实验",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "nagara-ai",
        category_id: "tech_life",
        rss_url: "https://anchor.fm/s/100b7bfdc/podcast/rss",
        title: "ながらAIラジオ",
        author: "usutaku/gomichan",
        cover_color: "#38b2ac",
        cover_label: "AI",
        level: Level::Advanced,
        tagline: "一周AI扫街",
        description: "",
        sort_order: 3,
    },
    ShowSeed {
        id: "robo-sync",
        category_id: "tech_life",
        rss_url: "https://anchor.fm/s/f01dd6e8/podcast/rss",
        title: "耳で学ぶAI、ロボシンク",
        author: "矢野 哲平",
        cover_color: "#2c7a7b",
        cover_label: "ロ",
        level: Level::Advanced,
        tagline: "工具一集讲透",
        description: "",
        sort_order: 4,
    },
    ShowSeed {
        id: "yuru-cs",
        category_id: "tech_life",
        rss_url: "https://api.robotstart.jp/api/v1/feeds/35ac047a/get-feeds/podcast",
        title: "ゆるコンピュータ科学ラジオ",
        author: "ゆるコンピュータ科学ラジオ",
        cover_color: "#4fd1c5",
        cover_label: "計",
        level: Level::Advanced,
        tagline: "科技吐槽有理",
        description: "",
        sort_order: 5,
    },
    ShowSeed {
        id: "sonnai-rika",
        category_id: "tech_life",
        rss_url: "https://sonnai.com/feed/rika",
        title: "そんない理科の時間",
        author: "そんないプロジェクト",
        cover_color: "#6b46c1",
        cover_label: "理",
        level: Level::Advanced,
        tagline: "一题一段理科",
        description: "",
        sort_order: 6,
    },
    ShowSeed {
        id: "chikyu-atsui",
        category_id: "tech_life",
        rss_url: "https://www.omnycontent.com/d/playlist/67122501-9b17-4d77-84bd-a93d00dc791e/7edbdd9d-5421-44be-8b03-b2b200ae9ce9/14852b35-caea-470d-9187-b2b200aea296/podcast.rss",
        title: "いま、地球がアツい！",
        author: "ニッポン放送",
        cover_color: "#2b6cb0",
        cover_label: "熱",
        level: Level::Advanced,
        tagline: "气候落到生活",
        description: "",
        sort_order: 7,
    },
    ShowSeed {
        id: "nou-life",
        category_id: "tech_life",
        rss_url: "https://feeds.megaphone.fm/TBS3591828566",
        title: "脳科学, 脳LIFE",
        author: "TBS RADIO",
        cover_color: "#38a169",
        cover_label: "脳",
        level: Level::Advanced,
        tagline: "把疑问交给大脑",
        description: "",
        sort_order: 8,
    },
    ShowSeed {
        id: "tonari-data",
        category_id: "tech_life",
        rss_url: "https://anchor.fm/s/dd122784/podcast/rss",
        title: "となりのデータ分析屋さん",
        author: "佐々木亮とたっちゃん",
        cover_color: "#1a202c",
        cover_label: "DA",
        level: Level::Expert,
        tagline: "AI进了工位",
        description: "",
        sort_order: 9,
    },
    ShowSeed {
        id: "rajireki",
        category_id: "history",
        rss_url: "https://anchor.fm/s/7296efc/podcast/rss",
        title: "ラジレキ 〜思わずシェアしたくなる歴史の話〜",
        author: "ラジレキ（ラジオ歴史小話）",
        cover_color: "#c53030",
        cover_label: "歴",
        level: Level::Beginner,
        tagline: "冷门掌故最上头",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "kikina-rekishi",
        category_id: "history",
        rss_url: "https://anchor.fm/s/d0c2344c/podcast/rss",
        title: "聞き流す歴史チャンネル/Podcast",
        author: "まお",
        cover_color: "#dd6b20",
        cover_label: "史",
        level: Level::Advanced,
        tagline: "史线一直走到今",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "nihonshi-radio",
        category_id: "history",
        rss_url: "https://anchor.fm/s/98cae28c/podcast/rss",
        title: "主に日本の歴史のことを話すラジオ",
        author: "KELLY OMRK",
        cover_color: "#e53e3e",
        cover_label: "日",
        level: Level::Advanced,
        tagline: "围桌聊透旧书史",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "gofun-history",
        category_id: "history",
        rss_url: "https://anchor.fm/s/f8ec4994/podcast/rss",
        title: "５分 de ヒストリー ～歴史・世界史・日本史・学び直し/クロノ",
        author: "クロノ",
        cover_color: "#2d3748",
        cover_label: "5",
        level: Level::Advanced,
        tagline: "通史拆成五分钟",
        description: "",
        sort_order: 3,
    },
    ShowSeed {
        id: "amari-nihonshi",
        category_id: "history",
        rss_url: "https://feeds.megaphone.fm/TRE5731924318",
        title: "あんまり役に立たない日本史",
        author: "TRIPLEONE",
        cover_color: "#c53030",
        cover_label: "日",
        level: Level::Advanced,
        tagline: "没用趣史更来劲",
        description: "",
        sort_order: 4,
    },
    ShowSeed {
        id: "jinbocho",
        category_id: "history",
        rss_url: "https://feeds.megaphone.fm/FUBI5605850457",
        title: "神保町で会いましょう",
        author: "FUBI",
        cover_color: "#38a169",
        cover_label: "神",
        level: Level::Advanced,
        tagline: "跟着街区学人文",
        description: "",
        sort_order: 5,
    },
    ShowSeed {
        id: "sengoku-yamajiro",
        category_id: "history",
        rss_url: "https://anchor.fm/s/10012fe20/podcast/rss",
        title: "西日本新聞 戦国山城Podcast",
        author: "西日本新聞社",
        cover_color: "#dd6b20",
        cover_label: "城",
        level: Level::Advanced,
        tagline: "地形本身会说话",
        description: "",
        sort_order: 6,
    },
    ShowSeed {
        id: "chikyu-discovery",
        category_id: "history",
        rss_url: "https://feeds.megaphone.fm/TBS2480913983",
        title: "ママタルトの地球ディッシュカバリー～東京外大の先生と一緒～",
        author: "TBS RADIO",
        cover_color: "#d69e2e",
        cover_label: "皿",
        level: Level::Advanced,
        tagline: "一桌菜讲一国史",
        description: "",
        sort_order: 7,
    },
    ShowSeed {
        id: "coten-radio",
        category_id: "history",
        rss_url: "https://anchor.fm/s/8c2088c/podcast/rss",
        title: "歴史を面白く学ぶコテンラジオ （COTEN RADIO）",
        author: "COTEN inc.",
        cover_color: "#2c5282",
        cover_label: "コ",
        level: Level::Advanced,
        tagline: "把帝国讲成人性",
        description: "",
        sort_order: 8,
    },
    ShowSeed {
        id: "heldio",
        category_id: "history",
        rss_url: "https://stand.fm/rss/650f4aef0bc9d6e1d67d6767",
        title: "【本・再放送】英語の語源が身につくラジオ (heldio)",
        author: "堀田隆一",
        cover_color: "#718096",
        cover_label: "語",
        level: Level::Expert,
        tagline: "从词根钻进人文",
        description: "",
        sort_order: 9,
    },
    ShowSeed {
        id: "unknown-wakaranai",
        category_id: "pop_culture",
        rss_url: "https://rss.buzzsprout.com/2611135.rss",
        title: "Unknown わからないいこと",
        author: "ap bank",
        cover_color: "#63b3ed",
        cover_label: "？",
        level: Level::Beginner,
        tagline: "文章自己开口",
        description: "",
        sort_order: 0,
    },
    ShowSeed {
        id: "ign-ginmaku",
        category_id: "pop_culture",
        rss_url: "https://jp.ign.com/podcast-ginmaku-podcast.xml",
        title: "IGN JAPAN 銀幕にポップコーン",
        author: "IGN JAPAN",
        cover_color: "#c53030",
        cover_label: "映",
        level: Level::Advanced,
        tagline: "先听风向再入戏",
        description: "",
        sort_order: 1,
    },
    ShowSeed {
        id: "kiku-zukan",
        category_id: "pop_culture",
        rss_url: "https://anchor.fm/s/10407d7f8/podcast/rss",
        title: "聞く図鑑",
        author: "学研の図鑑LIVE編集部",
        cover_color: "#4299e1",
        cover_label: "図",
        level: Level::Advanced,
        tagline: "图鉴里有日常",
        description: "",
        sort_order: 2,
    },
    ShowSeed {
        id: "shiten-soko",
        category_id: "pop_culture",
        rss_url: "https://feeds.megaphone.fm/SINC4746791863",
        title: "視点倉庫",
        author: "三宅香帆",
        cover_color: "#ed64a6",
        cover_label: "視",
        level: Level::Advanced,
        tagline: "观点能带回家",
        description: "",
        sort_order: 3,
    },
    ShowSeed {
        id: "eiga-hanashi",
        category_id: "pop_culture",
        rss_url: "https://virtualeigabar.com/feed/podcast/%e6%98%a0%e7%94%bb%e3%81%ae%e8%a9%b1%e3%81%97%e3%81%9f%e3%81%99%e3%81%8e%e3%82%8b%e3%83%a9%e3%82%b8%e3%82%aa/",
        title: "映画の話したすぎるラジオ",
        author: "映画の話したすぎるBAR",
        cover_color: "#f6e05e",
        cover_label: "映",
        level: Level::Advanced,
        tagline: "分歧越聊越亮",
        description: "",
        sort_order: 4,
    },
    ShowSeed {
        id: "rajimaga-essay",
        category_id: "pop_culture",
        rss_url: "https://feeds.megaphone.fm/rm-essay",
        title: "武田砂鉄 ラジオマガジン「ラジマガエッセイ」",
        author: "文化放送PodcastQR",
        cover_color: "#ecc94b",
        cover_label: "エ",
        level: Level::Advanced,
        tagline: "一周四种口气",
        description: "",
        sort_order: 5,
    },
    ShowSeed {
        id: "book-catalyst",
        category_id: "pop_culture",
        rss_url: "https://api.substack.com/feed/podcast/217357.rss",
        title: "ブックカタリスト",
        author: "goryugo",
        cover_color: "#2d3748",
        cover_label: "本",
        level: Level::Expert,
        tagline: "顺着一本往下读",
        description: "",
        sort_order: 6,
    },
    ShowSeed {
        id: "genji-monogatari",
        category_id: "pop_culture",
        rss_url: "https://www.omnycontent.com/d/playlist/5311a7b7-a30b-4811-ad95-aeba00eb9ec8/7e0ed04a-ad16-4878-a9f3-b0660022d0ad/5e49780b-5d0f-4094-bd03-b1bd00377edd/podcast.rss",
        title: "奥山景布子の『イマドキの源氏物語』",
        author: "産経新聞社",
        cover_color: "#6b46c1",
        cover_label: "源",
        level: Level::Expert,
        tagline: "古典被说活了",
        description: "",
        sort_order: 7,
    },
    ShowSeed {
        id: "higo-minwa",
        category_id: "pop_culture",
        rss_url: "https://feed.sonicbowl.cloud/rss/56d73b68-0cf3-4384-b19e-9a9d77d8196a/",
        title: "肥後の民話",
        author: "RKKラジオ",
        cover_color: "#c05621",
        cover_label: "肥",
        level: Level::Expert,
        tagline: "地方故事有包袱",
        description: "",
        sort_order: 8,
    },
];

/// RSS 主机只用于标记来源。解析不按平台分叉。
pub fn platform_of(rss_url: &str) -> &'static str {
    if rss_url.contains("anchor.fm") {
        "anchor"
    } else if rss_url.contains("megaphone.fm") {
        "megaphone"
    } else if rss_url.contains("libsyn.com") {
        "libsyn"
    } else if rss_url.contains("nhk.or.jp") {
        "nhk"
    } else if rss_url.contains("/feed/podcast") {
        "wordpress"
    } else {
        "rss"
    }
}
